ALTER TABLE "Cycle" ADD COLUMN "methodVersion" INTEGER NOT NULL DEFAULT 1, ADD COLUMN "rulesRevision" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Reference" ADD COLUMN "sourceRole" TEXT NOT NULL DEFAULT 'unspecified';
ALTER TABLE "Analysis" ADD COLUMN "portrait" JSONB;
CREATE TABLE "RuleBatch" (
 "id" TEXT PRIMARY KEY, "cycleId" TEXT NOT NULL REFERENCES "Cycle"(id) ON DELETE CASCADE ON UPDATE CASCADE,
 "inputHash" TEXT NOT NULL, "sourceSnapshot" JSONB NOT NULL, "candidates" JSONB NOT NULL, "notes" JSONB NOT NULL,
 "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "VoiceRule" (
 "id" TEXT PRIMARY KEY, "cycleId" TEXT NOT NULL REFERENCES "Cycle"(id) ON DELETE CASCADE ON UPDATE CASCADE,
 "batchId" TEXT REFERENCES "RuleBatch"(id) ON DELETE SET NULL ON UPDATE CASCADE,
 "candidateId" TEXT, "direction" TEXT NOT NULL, "text" TEXT NOT NULL, "category" TEXT NOT NULL DEFAULT '', "condition" TEXT NOT NULL DEFAULT '',
 "severity" TEXT NOT NULL DEFAULT 'none', "selected" BOOLEAN NOT NULL DEFAULT false, "sourceIds" JSONB NOT NULL DEFAULT '[]',
 "origin" TEXT NOT NULL DEFAULT 'reference', "editedByUser" BOOLEAN NOT NULL DEFAULT false, "archived" BOOLEAN NOT NULL DEFAULT false,
 "revision" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE INDEX "VoiceRule_cycleId_idx" ON "VoiceRule"("cycleId");
CREATE TABLE "RuleRevision" (
 "id" TEXT PRIMARY KEY, "ruleId" TEXT NOT NULL REFERENCES "VoiceRule"(id) ON DELETE CASCADE ON UPDATE CASCADE,
 "number" INTEGER NOT NULL, "snapshot" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX "RuleRevision_ruleId_number_key" ON "RuleRevision"("ruleId","number");
