'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from '@/lib/client';
import type {RuleInput,RuleCandidate} from '@/lib/method';
export type RuleView={id:string;batchId:string|null;candidateId:string|null;text:string;direction:'do'|'dont';severity:'none'|'soft'|'ban';category:string;condition:string;selected:boolean;sourceIds:string[];origin:string;editedByUser:boolean;archived:boolean;revision:number};
export type BatchView={id:string;createdAt:string;stale:boolean;sourceSnapshot:RuleInput;candidates:RuleCandidate[];notes:string[]};
type Draft=Pick<RuleView,'text'|'direction'|'severity'|'category'|'condition'|'selected'|'archived'>;
const draftOf=(r:RuleView):Draft=>({text:r.text,direction:r.direction,severity:r.severity,category:r.category,condition:r.condition,selected:r.selected,archived:r.archived});
const roleLabel:Record<string,string>={own:'Мой голос',inspiration:'Ориентир',unspecified:'Без роли'};
function RuleCard({rule,batch,refresh,dirty}:{rule:RuleView;batch?:BatchView;refresh:()=>void;dirty:(id:string,value:boolean)=>void}){
  const [draft,setDraft]=useState<Draft>(()=>draftOf(rule)),[status,setStatus]=useState('Сохранено'),[error,setError]=useState(''),[history,setHistory]=useState<{id:string;number:number;snapshot:Draft}[]>([]);
  const local=useRef(draft),saved=useRef(JSON.stringify(draft)),revision=useRef(rule.revision),busy=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),failed=useRef(false);
  useEffect(()=>{if(saved.current===JSON.stringify(local.current)&&!busy.current){const next=draftOf(rule);local.current=next;saved.current=JSON.stringify(next);revision.current=rule.revision;setDraft(next)}},[rule]);
  useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
  async function flush(){
    if(timer.current)clearTimeout(timer.current);if(busy.current||saved.current===JSON.stringify(local.current))return;
    if(!local.current.text.trim()){setError('Правило не может быть пустым');setStatus('Ошибка');return}
    busy.current=true;failed.current=false;const current={...local.current},signature=JSON.stringify(current);setStatus('Сохранение…');setError('');
    try{const result=await api<{rule:RuleView}>('rules/'+rule.id,'PATCH',{...current,expectedRevision:revision.current},true);revision.current=result.rule.revision;saved.current=signature;const pending=JSON.stringify(local.current)!==signature;dirty(rule.id,pending);setStatus(pending?'Ожидает сохранения':'Сохранено');refresh()}
    catch(e){failed.current=true;setStatus('Ошибка сохранения');setError(String(e)+' · Ваша формулировка осталась в поле. При конфликте скопируйте её перед обновлением страницы.');dirty(rule.id,true)}
    finally{busy.current=false;if(!failed.current&&saved.current!==JSON.stringify(local.current))timer.current=setTimeout(flush,0)}
  }
  function edit(change:Partial<Draft>,immediate=false){const next={...local.current,...change};local.current=next;setDraft(next);setStatus('Ожидает сохранения');dirty(rule.id,true);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(flush,immediate?0:800)}
  const sources=batch?.sourceSnapshot.sources.filter(source=>rule.sourceIds.includes(source.id))||[];
  const original=batch?.candidates.find(c=>c.id===rule.candidateId);
  return <article className={`rule-card ${draft.selected?'chosen':''}`}><label className="rule-select"><input type="checkbox" checked={draft.selected} onChange={e=>edit({selected:e.target.checked},true)}/><span>{draft.selected?'Включено в инструкцию':'Не включено'}</span>{draft.direction==='dont'&&<strong>{draft.severity==='ban'?'Запрет':'Нежелательно'}</strong>}</label><label>Формулировка<textarea aria-label="Формулировка правила" rows={3} value={draft.text} onChange={e=>edit({text:e.target.value})} onBlur={()=>flush()}/></label><details className="rule-settings"><summary>Условия и настройки правила</summary><div className="rule-fields"><label>Направление<select value={draft.direction} onChange={e=>edit({direction:e.target.value as 'do'|'dont',severity:e.target.value==='do'?'none':'soft'},true)}><option value="do">Делай так</option><option value="dont">Не делай так</option></select></label>{draft.direction==='dont'&&<label>Сила ограничения<select value={draft.severity} onChange={e=>edit({severity:e.target.value as 'soft'|'ban'},true)}><option value="soft">Нежелательно</option><option value="ban">Запрет</option></select></label>}<label>Категория<input value={draft.category} onChange={e=>edit({category:e.target.value})} onBlur={()=>flush()}/></label><label>Когда применять<input value={draft.condition} onChange={e=>edit({condition:e.target.value})} onBlur={()=>flush()} placeholder="Всегда или при определенном условии"/></label></div></details>
    <small>{rule.editedByUser?'Редакция пользователя · ':''}{rule.origin==='user'?'Пользовательское правило':'Из выбранных приемов'} · {status}</small>{error&&<div className="error" role="alert">{error}<div className="actions"><button className="ghost" onClick={()=>flush()}>Повторить сохранение</button><button className="ghost" onClick={()=>navigator.clipboard.writeText(draft.text)}>Скопировать правку</button></div></div>}
    <details><summary>Основания и исходное предложение</summary>{sources.map(source=><p key={source.id}><strong>{source.kind==='wish'?'Пожелание пользователя':source.kind==='constraint'?'Ограничение пользователя':roleLabel[source.role]}: </strong>{source.principle}</p>)}{!sources.length&&<p>Правило введено вручную.</p>}{original&&<div className="rule-original"><small>Предложено моделью</small><p>{original.text}</p>{original.text!==draft.text&&<><small>Текущая редакция</small><p>{draft.text}</p></>}</div>}{batch?.stale&&<p className="warning">Выбор приемов изменился после этого предложения.</p>}</details>
    <div className="actions"><button className="text-button" onClick={async()=>{const result=await api<{revisions:typeof history}>('rules/'+rule.id+'/revisions');setHistory(result.revisions)}}>История правок</button><button className="text-button" onClick={()=>edit({archived:!draft.archived},true)}>{draft.archived?'Вернуть правило':'Убрать из списка'}</button></div>{history.length>0&&<details open><summary>Сохраненные редакции</summary>{history.map(item=><div key={item.id} className="rule-history"><small>Редакция {item.number}</small><p>{item.snapshot.text}</p><small>{item.snapshot.selected?'Выбрано':'Не выбрано'} · {item.snapshot.severity}</small></div>)}</details>}
  </article>
}
export function RulesBoard({cycleId,rules,batches,warnings,busy,refresh,generate,assemble,onDirty}:{cycleId:string;rules:RuleView[];batches:BatchView[];warnings:string[];busy:boolean;refresh:()=>void;generate:()=>void;assemble:()=>void;onDirty:(dirty:boolean)=>void}){
  const [filter,setFilter]=useState('work'),[text,setText]=useState(''),[direction,setDirection]=useState<'do'|'dont'>('do'),[severity,setSeverity]=useState<'soft'|'ban'>('soft'),[error,setError]=useState(''),[creating,setCreating]=useState(false),[count,setCount]=useState(0);
  const dirtyIds=useRef(new Set<string>());
  function dirty(id:string,value:boolean){if(value)dirtyIds.current.add(id);else dirtyIds.current.delete(id);setCount(dirtyIds.current.size);onDirty(dirtyIds.current.size>0)}
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirtyIds.current.size){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>{window.removeEventListener('beforeunload',warn);onDirty(false)}},[onDirty]);
  const selected=rules.filter(r=>r.selected&&!r.archived),current=batches[0];
  const shown=rules.filter(r=>(filter==='archived'?r.archived:!r.archived)&&(filter==='work'?(r.selected||r.batchId===current?.id||!r.batchId):filter==='selected'?r.selected:filter==='new'?r.batchId===current?.id:filter==='manual'?r.origin==='user':true));
  const canMove=()=>!count||confirm('Есть несохраненные правки правил. Продолжить без них?');
  return <div className="rules-board"><div className="method-summary"><div><span className="eyebrow">Шаг 3 · превратите выбор в правила</span><h2>Делай так / Не делай так</h2><p>Отметьте правила, которые войдут в обе инструкции. Новые предложения не выбраны; снятие чекбокса не создает запрет.</p></div><div className="selection-totals"><span>Делай <strong>{selected.filter(r=>r.direction==='do').length}</strong></span><span>Нежелательно <strong>{selected.filter(r=>r.severity==='soft').length}</strong></span><span>Запрет <strong>{selected.filter(r=>r.severity==='ban').length}</strong></span></div></div><div className="actions"><button className="ghost" disabled={busy||count>0} onClick={generate}>{batches.length?'Предложить новые правила':'Сформировать кандидаты'}</button><button disabled={!selected.length||busy||count>0} onClick={()=>{if(canMove())assemble()}}>Собрать инструкцию из {selected.length} правил →</button></div><p className="hint">Повторная генерация добавит невыбранные кандидаты. Принятые правила и ручные формулировки сохранятся.</p>
    {current?.stale&&<p className="warning">Приемы или пожелания изменились. Последняя группа предложений основана на прежнем выборе; вы можете обновить её или сохранить свои правила.</p>}{warnings.map((warning,i)=><p className="warning" key={i}>{warning} Сохранение и экспорт доступны.</p>)}{current&&<details className="panel"><summary>Пояснения к последней группе · {new Date(current.createdAt).toLocaleString('ru')}</summary>{current.notes.length?current.notes.map((note,i)=><p key={i}>{note}</p>):<p>Спорные сочетания модель не указала.</p>}</details>}
    <div className="method-filters"><label>Показывать<select value={filter} disabled={count>0} onChange={e=>setFilter(e.target.value)}><option value="work">Выбранные и новые предложения</option><option value="all">Все правила и прежние предложения</option><option value="new">Последние предложения</option><option value="selected">Только выбранные</option><option value="manual">Пользовательские</option><option value="archived">Убранные из списка</option></select></label><details className="manual-rule"><summary>+ Свое правило</summary><label>Формулировка<textarea value={text} onChange={e=>setText(e.target.value)} rows={3}/></label><div className="actions"><select aria-label="Направление своего правила" value={direction} onChange={e=>setDirection(e.target.value as 'do'|'dont')}><option value="do">Делай так</option><option value="dont">Не делай так</option></select>{direction==='dont'&&<select aria-label="Сила своего ограничения" value={severity} onChange={e=>setSeverity(e.target.value as 'soft'|'ban')}><option value="soft">Нежелательно</option><option value="ban">Запрет</option></select>}<button disabled={!text.trim()||creating} onClick={async()=>{setCreating(true);try{await api('cycles/'+cycleId+'/manual-rules','POST',{rule:{text,direction,severity:direction==='do'?'none':severity,category:'Пользовательское',condition:'',selected:false}},true);setText('');setError('');refresh()}catch(e){setError(String(e))}finally{setCreating(false)}}}>Добавить невыбранное правило</button></div></details></div>{error&&<p className="error" role="alert">{error}</p>}
    <div className="rule-columns">{(['do','dont'] as const).map(side=><section className="rule-column" key={side}><h2>{side==='do'?'Делай так':'Не делай так'}</h2>{shown.filter(r=>r.direction===side).length===0&&<p className="muted">Здесь пока нет правил.</p>}{shown.filter(r=>r.direction===side).map(rule=><RuleCard key={rule.id} rule={rule} batch={batches.find(b=>b.id===rule.batchId)} refresh={refresh} dirty={dirty}/>)}</section>)}</div>
  </div>
}
