ALTER TABLE "AiJob"
  ADD COLUMN "stage" TEXT NOT NULL DEFAULT 'queued',
  ADD COLUMN "startedAt" TIMESTAMP(3),
  ADD COLUMN "progressChars" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "attemptCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "lastProgressAt" TIMESTAMP(3);
