import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:3333/',{waitUntil:'networkidle'});
await page.getByRole('heading',{name:/Соберите голос/}).waitFor();
await page.getByRole('link',{name:'Настройки'}).click();
await page.getByRole('button',{name:'Светлая'}).click();
await page.goto('http://127.0.0.1:3333/',{waitUntil:'networkidle'});
await page.evaluate(()=>document.fonts.ready);
const typography=await page.evaluate(()=>{
  const hero=getComputedStyle(document.querySelector('.hero h1'));
  const section=getComputedStyle(document.querySelector('.panel h2'));
  return {hero:hero.fontFamily,heroWeight:hero.fontWeight,heroStyle:hero.fontStyle,section:section.fontFamily,loadedOswald:document.fonts.check('400 48px Oswald','Соберите голос'),loadedHuninn:document.fonts.check('400 28px Huninn','Проекты')};
});
assert.match(typography.hero,/Oswald/);assert.equal(typography.heroWeight,'400');assert.equal(typography.heroStyle,'normal');
assert.match(typography.section,/Huninn/);assert.equal(typography.loadedOswald,true);assert.equal(typography.loadedHuninn,true);
await page.screenshot({path:'/tmp/ai_voicers_light.png',fullPage:true});
await page.getByRole('link',{name:/Ангел/}).click();
await page.getByText(/контекст 1.048.576 токенов/).waitFor();
await page.locator('.analysis-block .element').first().waitFor();
assert.ok((await page.locator('.analysis-block .element').count())>=1);
await page.locator('.job-card.succeeded').first().waitFor();
await page.screenshot({path:'/tmp/ai_voicers_analysis_status.png',fullPage:true});
await page.getByRole('tab',{name:'Результат'}).click();
const documentFont=await page.locator('.doc-text').first().evaluate(node=>getComputedStyle(node).fontFamily);
assert.match(documentFont,/Huninn/);
await page.screenshot({path:'/tmp/ai_voicers_workspace.png',fullPage:true});
await page.setViewportSize({width:360,height:780});
const workOverflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);
assert.ok(workOverflow<=1,`workspace overflow: ${workOverflow}px`);
await page.setViewportSize({width:1440,height:900});
await page.getByRole('link',{name:'Настройки'}).click();
await page.getByRole('button',{name:'Темная'}).click();
await page.waitForTimeout(300);
assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
await page.screenshot({path:'/tmp/ai_voicers_dark.png',fullPage:true});
await page.setViewportSize({width:360,height:780});
await page.reload({waitUntil:'networkidle'});
assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
const scroll=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);
assert.ok(scroll<=1,`horizontal overflow: ${scroll}px`);
await page.screenshot({path:'/tmp/ai_voicers_mobile.png',fullPage:true});
await page.keyboard.press('Tab');
assert.ok(await page.evaluate(()=>document.activeElement!==document.body));
assert.deepEqual(errors,[]);
await page.getByRole('button',{name:'Светлая'}).click();
console.log(JSON.stringify({status:'passed',typography,documentFont,mobileOverflow:scroll,workspaceOverflow:workOverflow,pageErrors:errors.length}));
await browser.close();
