import assert from 'node:assert/strict';
import pg from 'pg';
const origin='http://localhost:3000';
async function call(path,method='GET',body,idem=false){
  const response=await fetch(origin+'/api/v1/'+path,{method,headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{'Origin':origin}:{}),...(idem?{'Idempotency-Key':crypto.randomUUID()}:{})},body:body===undefined?undefined:JSON.stringify(body)});
  const value=await response.json();
  if(!response.ok)throw new Error(`${path}: ${response.status} ${JSON.stringify(value)}`);
  return value;
}
async function wait(id){for(let n=0;n<60;n++){const r=await call('jobs/'+id);if(r.job.state==='succeeded')return;if(['failed','canceled'].includes(r.job.state))throw new Error(`job ${id}: ${r.job.errorCode}`);await new Promise(r=>setTimeout(r,500));}throw new Error('job timeout')}
const settings=await call('settings');
assert.equal(settings.adapter,'test');
const created=await call('projects','POST',{name:'Тестовый проект',modelId:'test/model'});
const projectId=created.project.id, cycleId=created.project.cycles[0].id;
let data=await call('cycles/'+cycleId);
assert.equal(data.references.length,5);
const ref=data.references[0], secretMarker='НЕПЕРЕДАВАТЬ_ИСХОДНИК_123';
const source='Короткий текст. Затем очень длинная фраза, которая меняет темп. '+secretMarker;
await call('references/'+ref.id,'PATCH',{expectedRevision:ref.revision,text:source,author:'Имя автора для изоляции'});
let current=await call('cycles/'+cycleId);
const analysis=await call('references/'+ref.id+'/analyses','POST',{depth:'detailed'},true);await wait(analysis.jobId);
current=await call('cycles/'+cycleId);
assert.equal(current.cycle.locked,true);
const a=current.references[0].analyses[0];assert.equal(a.elements.length,1);
await call('cycles/'+cycleId+'/selection','PATCH',{analysisId:a.id,elementId:a.elements[0].id,state:'selected'});
current=await call('cycles/'+cycleId);
await call('cycles/'+cycleId+'/selection-settings','PATCH',{expectedRevision:current.cycle.revision,wishes:'Добавь спокойную иронию',constraints:[{kind:'ban',text:'Не использовать канцеляризмы'}]});
const assembly=await call('cycles/'+cycleId+'/assemblies','POST',{},true);await wait(assembly.jobId);
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL});
const payload=(await pool.query('SELECT input FROM "AiJob" WHERE id=$1',[assembly.jobId])).rows[0].input;
assert.ok(!JSON.stringify(payload).includes(secretMarker));
assert.ok(!JSON.stringify(payload).includes('Имя автора'));
assert.ok(!JSON.stringify(payload).includes('quote'));
current=await call('cycles/'+cycleId);
const proposal=current.proposals.find(p=>p.kind==='full'&&!p.applied);assert.ok(proposal);
await call('cycles/'+cycleId+'/proposals/'+proposal.id,'PATCH',{expectedRevision:current.cycle.fullRevision},true);
current=await call('cycles/'+cycleId);
assert.ok(current.cycle.fullText);
await call('cycles/'+cycleId+'/draft','PATCH',{kind:'full',text:current.cycle.fullText+'\nРучная правка.',expectedRevision:current.cycle.fullRevision});
const prompt=await call('cycles/'+cycleId+'/prompt-versions','POST',{},true);await wait(prompt.jobId);
current=await call('cycles/'+cycleId);
const pp=current.proposals.find(p=>p.kind==='prompt'&&!p.applied);assert.ok(pp);
await call('cycles/'+cycleId+'/proposals/'+pp.id,'PATCH',{expectedRevision:current.cycle.promptRevision},true);
current=await call('cycles/'+cycleId);
const version=await call('cycles/'+cycleId+'/versions','POST',{name:'Первый снимок',expectedRevision:current.cycle.revision},true);
const frozen=version.version.snapshot.fullText;
await call('cycles/'+cycleId+'/draft','PATCH',{kind:'full',text:current.cycle.fullText+'\nПоздняя правка.',expectedRevision:current.cycle.fullRevision});
current=await call('cycles/'+cycleId);
assert.equal(current.versions[0].snapshot.fullText,frozen);
const sample=await call('cycles/'+cycleId+'/samples','POST',{document:'prompt',situation:'Короткая прогулка',words:150},true);await wait(sample.jobId);
const check=await call('cycles/'+cycleId+'/checks','POST',{document:'full'},true);await wait(check.jobId);
current=await call('cycles/'+cycleId);
assert.equal(current.samples.length,1);assert.equal(current.checks.length,1);
const exportResponse=await fetch(origin+`/api/v1/exports?cycleId=${cycleId}&kind=full&format=md`);
assert.equal(await exportResponse.text(),current.cycle.fullText);
const usage=await call('cycles/'+cycleId+'/usage');assert.ok(usage.totalTokens>=150);
const key='sk-or-test-only-1234567890';
await call('settings/credential','POST',{key});
const masked=await call('settings');assert.ok(masked.credential.mask);assert.ok(!JSON.stringify(masked).includes(key));
const stored=(await pool.query('SELECT "cipherText" FROM "Credential" LIMIT 1')).rows[0].cipherText;assert.ok(!stored.includes(key));
await pool.end();
console.log(JSON.stringify({status:'passed',projectId,cycleId,versionId:version.version.id,usage:usage.totalTokens,checks:['analysis','selection','payload','proposal','manual-edit','prompt','version','sample','check','export','credential']}));
